workflows:
  ios-app-store:
    name: iOS App Store
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: buscamotobrasil
    environment:
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: "br.com.buscamotobrasil.app"
        XCODE_WORKSPACE: "src/Busca Moto Brasil.xcworkspace"
        XCODE_SCHEME: "Busca Moto Brasil"
    scripts:
      - name: Set up certificate and profile
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo $CM_PROVISIONING_PROFILE | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
          PROFILE_UUID=$(security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision | plutil -extract UUID raw -)
          mv ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision
          security create-keychain -p "" build.keychain
          security import /tmp/certificate.p12 -k ~/Library/Keychains/build.keychain -P $CM_CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Librar
